FROM postgres
MAINTAINER Frank Pommerening "frank@pommerening-online.de"
ENV REFRESHED_AT 2016-03-09
ENV POSTGRES_USER spartakiade
ENV POSTGRES_PASSWORD SportF3
ADD init.sql /docker-entrypoint-initdb.d/

