from  dduportal/docker-compose
MAINTAINER Frank Pommerening "frank@pommerening-online.de"
ENV REFRESHED_AT 2016-03-18
RUN mkdir /compose
COPY compose/* /compose/
WORKDIR /compose/
ENTRYPOINT ["/bin/bash"]
