from  dduportal/docker-compose
MAINTAINER Frank Pommerening "frank@pommerening-online.de"
ENV REFRESHED_AT 2016-03-06
RUN mkdir /componse
COPY compose/* /componse/
WORKDIR /componse/
ENTRYPOINT ["/bin/bash"]
